"""Generate the shared file tree's PDF fixtures at seed time.

Text-layer invoices and the W-9 are written with a real font so pypdf can
extract their text. The scanned invoice is rasterized to an image and embedded
in a PDF, so it has no text layer by construction. Every PDF carries a fixed
creation date, keeping the generated bytes reproducible across seeds.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from fpdf import FPDF
from PIL import Image, ImageDraw, ImageFont

from mocks.seed.scenarios import (
    SCANNED,
    SCENARIOS,
    VENDOR_ONBOARDING,
    InvoiceScenario,
    VendorOnboardingScenario,
)

INVOICE_DIR = Path("documents") / "invoices"
ONBOARDING_DIR = Path("documents") / "vendor-onboarding"

INVOICE_DATE = "2026-09-05"
ONBOARDING_DATE = "2026-09-04"
PDF_CREATED_AT = datetime(2026, 9, 5, 9, 0, 0, tzinfo=UTC)


def invoice_relpath(scenario: InvoiceScenario) -> Path:
    return INVOICE_DIR / f"{scenario.invoice_number}.pdf"


def tax_form_relpath(scenario: VendorOnboardingScenario) -> Path:
    return ONBOARDING_DIR / scenario.tax_form_filename


def write_documents(shared_root: Path) -> None:
    shared_root = Path(shared_root)
    for scenario in SCENARIOS:
        path = shared_root / invoice_relpath(scenario)
        path.parent.mkdir(parents=True, exist_ok=True)
        if scenario.key == SCANNED.key:
            write_scanned_invoice(path, scenario)
        else:
            write_invoice(path, scenario)
    form_path = shared_root / tax_form_relpath(VENDOR_ONBOARDING)
    form_path.parent.mkdir(parents=True, exist_ok=True)
    write_tax_form(form_path, VENDOR_ONBOARDING)


def _invoice_lines(scenario: InvoiceScenario) -> list[str]:
    return [
        "INVOICE",
        f"Vendor: {scenario.vendor_name}",
        f"Invoice number: {scenario.invoice_number}",
        f"Purchase order: {scenario.po_id or 'none'}",
        f"Goods receipt: {scenario.gr_id or 'none'}",
        f"Amount due: {scenario.invoice_amount_cents / 100:,.2f} USD",
        f"Invoice date: {INVOICE_DATE}",
        "Payment terms: Net 30",
    ]


def _new_pdf() -> FPDF:
    pdf = FPDF()
    pdf.set_creation_date(PDF_CREATED_AT)
    pdf.add_page()
    return pdf


def write_invoice(path: Path, scenario: InvoiceScenario) -> None:
    pdf = _new_pdf()
    pdf.set_font("Helvetica", size=12)
    y = 20
    for line in _invoice_lines(scenario):
        pdf.text(15, y, line)
        y += 8
    pdf.output(str(path))


def write_scanned_invoice(path: Path, scenario: InvoiceScenario) -> None:
    page = Image.new("RGB", (1275, 1650), "white")
    draw = ImageDraw.Draw(page)
    heading = ImageFont.load_default(size=36)
    body = ImageFont.load_default(size=22)
    draw.text((80, 100), "INVOICE", fill="black", font=heading)
    for offset, line in enumerate(_invoice_lines(scenario)[1:]):
        draw.text((80, 200 + offset * 50), line, fill="black", font=body)

    pdf = _new_pdf()
    pdf.image(page, x=0, y=0, w=210)
    pdf.output(str(path))


def write_tax_form(path: Path, scenario: VendorOnboardingScenario) -> None:
    pdf = _new_pdf()
    pdf.set_font("Helvetica", size=12)
    y = 20
    for line in [
        "Form W-9",
        "Request for Taxpayer Identification Number and Certification",
        f"Name: {scenario.company_name}",
        f"Business name: {scenario.company_name}",
        f"Taxpayer Identification Number: {scenario.tax_id}",
        f"Address: {scenario.address}",
        f"Email: {scenario.contact_email}",
        f"Signature: {scenario.contact_name}",
        f"Date: {ONBOARDING_DATE}",
    ]:
        pdf.text(15, y, line)
        y += 8
    pdf.output(str(path))
